const data = {
  products: [
    {
      id: "1",
      title: "Nike slim shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: "2",
      title: "Adidas shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4,
      numReviews: 8,
      description: "high quality shirt",
    },
    {
      id: "3",
      title: "Lacoste shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 150,
      countInStock: 0,
      brand: "Nike",
      rating: 5,
      numReviews: 17,
      description: "high quality shirt",
    },
    {
      id: "4",
      title: "Nike slim pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 79.99,
      countInStock: 25,
      brand: "Nike",
      rating: 4.5,
      numReviews: 11,
      description: "high quality pants",
    },
    {
      id: "5",
      title: "Adidas pants",
      category: "pants",
      image: "/images/p5.jpg",
      price: 100,
      countInStock: 15,
      brand: "Adidas",
      rating: 4,
      numReviews: 8,
      description: "high quality pants",
    },
    {
      id: "6",
      title: "Lacoste pants",
      category: "pants",
      image: "/images/p6.jpg",
      price: 150,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      numReviews: 17,
      description: "high quality pants",
    },
  ],
};

export default data;
